bespoken/bst

.gitignore
README.md
TODO.md
TUTORIAL_JAVA.md
TUTORIAL_NODE.md
lib/client/bespoke-client.ts
package.json
samples/java/README.md
samples/java/pom.xml

This updates the occurrences of `bespoke` to `bespoken` to reflect the new repository.  The file names still needs to be updated however this will be a separate RP.

Updated bespoke --> bespoken in Documentation

---

README.md
docs/SKILL_CONFIGURATION.md
docs/TUTORIAL_JAVA.md
docs/TUTORIAL_NODE.md

Updates for styling and consistency as well as a new Skill Configuration doc.

Documentation Updates

---

.gitignore
.travis.yml
README.md
package.json

Coveralls.io will check code coverage on travis-ci builds.

Adds Coveralls.io

---

README.md

Adds the NPM badge to the readme to quickly communicate to the user that we are available through NPM and what the most current version is.

NPM Version Badge

---

.gitignore
DEVELOPER.md
README.md
lib/client/lambda-runner.ts
lib/core/file-util.ts
lib/core/node-util.ts
lib/core/string-util.ts
test/bin/bst-proxy-test.ts
test/bin/bst-server-test.ts
test/bin/bst-test.ts
test/client/lambda-runner-test.ts
test/core/string-util-test.ts
test/resources/ExampleLambda2.js
test/resources/ExampleLambdaCopy.js
test/resources/exampleProject/ExampleLambda.js
test/resources/exampleProject/ExampleModule.js

Auto reload#12

---

bin/bst-proxy.ts
test/bin/bst-proxy-test.ts

Added print out for urlgen as well as better test

---

DEVELOPER.md
bin/bst-proxy.ts
bin/bst.ts
lib/client/bespoke-client.ts
lib/client/bst-proxy.ts
lib/client/keep-alive.ts
lib/core/logging-helper.ts
lib/core/socket-handler.ts
lib/server/node-manager.ts
test/bin/bst-proxy-test.ts
test/client/bespoke-client-test.ts
test/client/keep-alive-test.ts
test/core/logging-helper-test.ts
test/core/socket-handler-test.ts
test/server/bespoke-server-test.ts
test/server/node-manager-test.ts

Client fix#16

---

package.json

As pointed out by redditor [/u/jjaquinta](https://www.reddit.com/r/AmazonEchoDev/comments/4zwrz7/test_your_alexa_skill_directly_on_an_echo_while/d71w52n?st=ishs3709&sh=4139944e)

Fix for Conflicting LICENSE Information

---

lib/client/tcp-client.ts
lib/core/socket-handler.ts
lib/server/node-manager.ts
test/alexa/skill-invoker-test.ts
test/core/socket-handler-test.ts
test/server/node-manager-test.ts

Better error-handling

---

.gitignore
DEVELOPER.md
docs/assets/css/style.css
docs/index.md
mkdocs.yml

Mobile Docs Fix for Badge Images 

---

docs/index.md

Take a look here to see what I mean:
https://bst.readthedocs.io/en/latest/

Trying to fix the bullet points showing strangely in RTD

---

README.md
docs/index.md
docs/tutorials/tutorial_flask_ask_python.md
docs/tutorials/tutorial_lambda_nodejs.md
docs/tutorials/tutorial_local_server_java.md
mkdocs.yml

Simple tutorial using bst with python and flask-ask.

Flask-Ask Python Tutorial

---

docs/api_readme.md
lib/client/lambda-server.ts
package.json

Fixes up bad tagging with 0.7.0 - misalignment between docs and library

Version 0 7 1

---

docs/api/classes/bstalexa.html
docs/api/classes/bstalexaevents.html
docs/api/classes/lambdaserver.html
docs/api/index.html
lib/server/webhook-manager.ts

Removed server debugging

---

bin/bst-speak.ts
lib/alexa/interaction-model.ts
lib/core/global.ts
lib/core/node-util.ts
test/bin/bst-speak-test.ts
test/client/bst-alexa-test.ts
test/core/global-test.ts

Clearer error messages

---

README.md
bin/bst-intend.ts
bin/bst-sleep.ts
bin/bst-speak.ts
bin/bst.ts
docs/commands/intend.md
docs/commands/speak.md
docs/index.md
lib/client/bst-alexa.ts
lib/core/global.ts
mkdocs.yml
package.json
test/bin/bst-intend-test.ts
test/bin/bst-speak-test.ts

Bst intend#105

---

lib/alexa/alexa-context.ts
lib/alexa/service-request.ts
test/alexa/service-request-test.ts

Fixed issue with requestID being sent instead of requestId

---

docs/api/classes/audioitem.html
docs/api/classes/audioitemstream.html
docs/api/classes/bstalexa.html
docs/api/classes/bstalexaevents.html
docs/api/classes/bstencode.html
docs/api/classes/lambdaserver.html
docs/api/classes/logless.html
docs/api/interfaces/awsencoderconfig.html
docs/api/interfaces/lambdafunction.html
lib/logless/logless-context.ts
package.json
test/logless/logless-test.ts

Transaction id#152

---

lib/server/statistics.ts
test/server/statistics-test.ts

Updates for stats tracking

---

docs/api/classes/alexacontext.html
docs/api/classes/alexasession.html
docs/api/classes/audioitem.html
docs/api/classes/audioitemstream.html
docs/api/classes/bstalexa.html
docs/api/classes/bstalexaevents.html
docs/api/classes/bstencode.html
docs/api/classes/lambdaserver.html
docs/api/classes/log.html
docs/api/classes/logless.html
docs/api/classes/loglesscontext.html
docs/api/classes/loglessmiddleware.html
docs/api/enums/logtype.html
docs/api/interfaces/expresserrorhandler.html
docs/api/interfaces/expressrequesthandler.html
docs/api/interfaces/iencoderconfig.html
docs/api/interfaces/lambdafunction.html
package.json

Version0 9 31

---

lib/client/bst-alexa.ts
test/client/bst-alexa-test.ts

Set app id from the config file if exists and no application ID was provided

Preserve app id#229

---

lib/client/bst-config.ts
lib/client/bst-proxy.ts
lib/external/spokes.ts
test/external/spokes-test.ts

Fix missing parameters in spokes pipe creation

---

bin/bst-deploy.ts
bin/bst-intend.ts
bin/bst-launch.ts
bin/bst-proxy.ts
bin/bst-server.ts
bin/bst-sleep.ts
bin/bst-speak.ts
bin/bst.ts
lib/client/bst-config.ts
lib/external/source-name-generator.ts
lib/external/spokes.ts
test/bin/bst-test.ts
test/client/bst-config-test.ts
test/external/request-error.ts
test/external/source-name-generator-test.ts
test/external/spokes-test.ts

This attempts to fix the issues we have with the external services by adding timeouts to the requests. Local test runs are still unstable, but want to also check in travis CI

Add timeout and timeout error on external service calls (Closes #257)

---

lib/client/bst-alexa.ts
test/client/bst-alexa-test.ts

Fixes issue with config being required for programmatic use

---

gulpfile.js
lib/client/lambda-deploy.ts
lib/client/module-manager.ts

This one fixes #276 by using node path management, main issue is that tests don't run in windows right now if you download the project, but i did manual testing to check that we can use the lambda server programmatically.
Windows test will be solved as part of a different issue.

Module manager windows path#276

---

test/bin/bst-speak-test.ts
test/client/bst-config-test.ts

- Reenable test for bst-speak
- Mock source-generator and spokes test

Mock source generator and spokes#255

---

bin/bst-proxy.ts
bin/bst.ts
lib/client/bst-config.ts
lib/core/logging-helper.ts
test/bin/bst-test.ts

Correct proxy dashboard url message.
Add error logs to bst folder before exiting bst

Issues pre-version 1.0

---

test/client/bespoke-client-test.ts

Use a different port for each node version

---

docs/index.md
lib/logless/logless-context.ts
package-lock.json
package.json
test/logless/logless-test.ts

Assure continuation logless looks for our own context 

---

circle.yml

Take different AWS credentials for hyper deploy

---

.travis.yml
circle.yml

Add Travis for branches and restrict Circle for Master and Deploys

---

.travis.yml
gulpfile.js
package-lock.json
package.json

Add coveralls to travis builds

---

docs/tutorials/tutorial_lambda_nodejs.md

Referenced project has been deprecated, but still available at a different link

Fixed broken urls

---

bin/bst-speak.ts
lib/client/lambda-server.ts
lib/core/global.ts
test/client/lambda-server-test.ts
test/core/global-test.ts

- Fix issue with proxy lambda where file is used but url is changed (#395)
- Dashboard url for proxy needs to use apps.bespoken.io/dashboard
- Missing mock

Fixes Pre Release of Version 1.1.1

---

bin/bst-speak.ts
lib/client/bst-config.ts
lib/external/virtual-device.ts
package.json
test/bin/bst-speak-test.ts
test/external/silent-echo-test.ts

virtual-device-sdk

---

bin/bst-intend.ts
bin/bst-launch.ts
bin/bst-proxy.ts
bin/bst-utter.ts
lib/client/bespoke-client.ts
lib/client/lambda-server.ts
package-lock.json
package.json
test/bin/bst-launch-test.ts

Add colors according to #408 
Sample Results
URL for BST proxy and error messages 
Request and Responses

Color coding output#408

---

bin/bst-intend.ts
bin/bst-launch.ts
bin/bst-proxy.ts
bin/bst-utter.ts
lib/client/bespoke-client.ts
lib/client/lambda-server.ts
lib/core/global.ts
lib/core/logging-helper.ts
package.json

Relates to #408 
Sample of the Changes

Change blue to bespoken orange in Request Payloads and Links

---

lib/client/bespoke-client.ts
test/client/bespoke-client-test.ts

This reconnects on self disconnect or disconnect from server. 
Attempts to reconnect waiting first 1, then 2, then 3 seconds.
Still misses an error on keep alive failed, that seems unrelated to the change.

Reconnect after disconnection

---

lib/client/bespoke-client.ts
lib/client/keep-alive.ts
lib/client/tcp-client.ts
lib/core/http-buffer.ts
lib/core/socket-handler.ts
lib/core/webhook-request.ts
lib/server/node-manager.ts
lib/server/node.ts
test/client/bespoke-client-test.ts
test/client/keep-alive-test.ts
test/core/socket-handler-test.ts
test/server/bespoke-server-test.ts

Relates #393
- Support binary data 
- Resolve Windows failing test for Bespoke-client-test (node "setTimeout" seems to be slower than mocha "this.timeout" )

Support Binary Data

---

bin/bst-intend.ts
bin/bst-launch.ts
bin/bst-utter.ts
lib/client/bst-virtual-alexa.ts
test/client/bst-virtual-alexa-test.ts
test/resources/nonUSModel/models/de-DE.json

Integrate locale changes

---

lib/client/lambda-server.ts

https://github.com/bespoken/bst/issues/440
handler returns Promise in v2

support (Alexa) ASK SDK v2

---

bin/bst-speak.ts
test/bin/bst-test.ts

display locale and voice id option on speak command

---

package-lock.json
package.json

Depends on https://github.com/bespoken/skill-testing-ml/pull/120 being merge, relates to #508

Bst test jest run in band

---

package.json

Relates to #501 
Depends on https://github.com/bespoken/skill-testing-ml/pull/122 being merged

Use latests skill testing for exclude and include tags

---

bin/bst-speak.ts
lib/external/virtual-device.ts
test/external/virtual-device-test.ts

Send friendly message on virtual device error, log error to bst-debug

---

bin/bst-test.ts

Indicate e2e is available on help section on bst-test

---

.circleci/config.yml

migrate to ecs

---

bin/bst-proxy.ts

Remove source creation link from bst proxy

---

.circleci/config.yml

Statistics was disabled for all deploys, we also manually edited .env file

Update Config.yml to enable statistics

---

bin/bst-test.ts
lib/external/virtual-device.ts
package-lock.json
package.json
test/bin/bst-test-test.ts
test/external/virtual-device-test.ts

relates to https://github.com/bespoken/bst/issues/584

Update libraries and call client parameter with 'CLI'

---

bin/bst.ts

Add Version option

---

package-lock.json
package.json

Version2 4 0

---

bin/bst-init.ts

FEAT-595: fix dialogFlow question for unit/google flow

---

bin/bst-init.ts
bin/bst.ts
lib/init/init-util.ts
test/init/init-util-test.ts

FEAT-595: text changes, specific extension for e2e test

---

bin/bst-init.ts

FEAT-595: update welcome message on init command

---

bin/bst-init.ts
package-lock.json

FEAT-595: update farewell message

---

bin/bst-init.ts
gulpfile.js
lib/init/init-util.ts
test/init/init-util-test.ts

FEAT-624: Update bst Init testing.json file

---

bin/bst-speak.ts
lib/core/global.ts
package-lock.json

Change bst-speak displayed url

---

lib/external/messages.ts
lib/external/source-name-generator.ts
lib/external/spokes.ts
package-lock.json
package.json
test/external/source-name-generator-test.ts
test/external/spokes-test.ts
tsconfig.json
tslint.json

Relates to https://github.com/bespoken/bst/issues/602﻿

Add support for HTTPS_PROXY, fix typescript issues

---

test/bin/bst-intend-test.ts

Relates to https://github.com/bespoken/bst/issues/451﻿

Add mock functions to avoid a process.exit error

---

README.md

Looks like you wanted this link: https://read.bespoken.io/unit-testing/getting-started/

README.md has bad link to Unit Testing

---

package-lock.json
package.json

- Pointing skill-testing-ml 1.3.1-RC.1

Using version to point skill-testing-ml 1.3.1-RC.1

---

bin/bst-test.ts

PR: https://github.com/bespoken/dashboard/issues/2096
- Set monitoring value for client attribute when execute on Github action

Add routine to check if it's running on Github action

---

package-lock.json
package.json

PR: https://github.com/bespoken/dashboard/issues/2095
- Added skill-testing-ml new version for email notification service

Set skill-testing-ml to 1.4.4-alpha.1

---

package-lock.json
package.json

PR: https://github.com/bespoken/dashboard/issues/2095
- Added alpha version of skill-testing-ml

Feat adding email notification by max

---

package-lock.json
package.json

PR: https://github.com/bespoken/dashboard/issues/2095
- Update skill-testing-ml with changes for email notificartion

Update skill-testing-ml for email notification

---

package-lock.json
package.json

- Update skill-testing-ml with version 1.4.6-alpha.1

Update to skill-testing-ml version 1.4.6-alpha.1
